# -*- coding: utf-8 -*-
"""College Inquiry  Chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x04qmmMgYj89z1yEY-J5cw-7kIiXRkvr

# Required Packages:
The required python packages are as follows, (here we have mentioned the packages with versions that we have used for the developments)
we are going to require some Python built-ins, as well as popular libraries for NLP, deep learning, as well as the defacto library NumPy which is great for dealing with arrays.
"""

import json
import string
import random
import pickle
import nltk
import numpy as np
import matplotlib.pyplot as plt

from nltk.stem import WordNetLemmatizer
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout,Activation
from tensorflow.keras.optimizers import Adam
nltk.download("punkt")
nltk.download("wordnet")
nltk.download('omw-1.4')

"""# Define Intents
We had defined a few simple intents and bunch of messages corresponding to those intents and also map some responses according to each intent category.
 JSON file named “intents.json” is created including this data as follows.

Within this intents JSON file, alongside each intents tag and pattern, there
will be responses.
However, for our chatbot, these responses are not going to be generated.
What this means is that our patterns aren’t going to be as free-flowing as the patterns users can ask (it will not adapt), instead, the responses will be using static responses that the chatbot will return when posed with a query.
"""

data={
  "intents": [
    {
      "tag": "greeting",
      "patterns": [
        "Hi there",
        "How are you",
        "Is anyone there?",
        "Hey",
        "Hello",
        "Good day",
        "Namaste",
        "yo"
      ],
      "responses": [
        "Hello! How can I help you?",
        "Hi! How may I assist you?",
        "Hey there! How can I assist with your inquiry?",
        "Namaste! How can I help you with your doubts?"
      ]
    },
    {
      "tag": "school_strengths",
      "patterns": [
        "What are your school's strengths?",
        "Tell me about the strengths of your school"
      ],
      "responses": [
        "At Shri Ramdeobaba College of Engineering and Management, our strengths lie in providing quality education, state-of-the-art facilities, experienced faculty, industry exposure, and a vibrant student community."
      ]
    },
    {
      "tag": "administrators_accessibility",
      "patterns": [
        "How accessible are administrators, registrars, financial aid officers, etc.?",
        "Can I easily reach administrators, registrars, financial aid officers, etc.?"
      ],
      "responses": [
        "Our college administrators, registrars, and financial aid officers are easily accessible and always willing to assist students with their queries and concerns."
      ]
    },
    {
      "tag": "popular_majors",
      "patterns": [
        "What majors are popular?",
        "Which programs are popular?",
        "What are the popular majors?",
        "Tell me about the popular courses"
      ],
      "responses": [
        "Some of the popular majors at Shri Ramdeobaba College of Engineering and Management include Computer Science, Information Technology, Artificial Intelligence and Machine Learning, and Data Science."
      ]
    },
    {
      "tag": "reputable_departments",
      "patterns": [
        "What departments or programs have the best reputations?",
        "Which departments are well-known?",
        "Tell me about reputable programs."
      ],
      "responses": [
        "All departments and programs at our college have a great reputation for providing quality education and producing skilled professionals. We take pride in the accomplishments and achievements of our students and faculty across all disciplines."
      ]
    },
    {
      "tag": "professor_office_hours",
      "patterns": [
        "Do your professors hold office hours?",
        "Are professors available for student meetings outside of class?"
      ],
      "responses": [
        "Absolutely! Our professors hold regular office hours to provide additional support and guidance to students. They are more than willing to meet with students outside of class to discuss any academic or research-related matters."
      ]
    },
    {
      "tag": "lecture_vs_discussion_classes",
      "patterns": [
        "Are most of your classes lecture-based or discussion-based?",
        "What is the teaching style in classes?"
      ],
      "responses": [
        "The teaching style at Shri Ramdeobaba College of Engineering and Management varies depending on the course and faculty. Some classes follow a lecture-based approach, while others may emphasize interactive discussions and group activities."
      ]
    },
    {
      "tag": "reading_and_writing_requirements",
      "patterns": [
        "How much reading and writing is required in your courses?",
        "Are there extensive reading and writing assignments?"
      ],
      "responses": [
        "The reading and writing requirements in our courses may vary. Some courses may have more reading assignments, while others may involve practical projects and presentations. However, our academic programs aim to strike a balance between theoretical knowledge and practical application."
      ]
    },
    {
      "tag": "collaborative_work_requirement",
      "patterns": [
        "How often are collaborative work or group presentations required?",
        "Do students work together on projects?"
      ],
      "responses": [
        "Collaborative work and group presentations are essential components of our courses. We encourage students to work together, fostering teamwork and communication skills that are vital in real-world scenarios."
      ]
    },
    {
      "tag": "academic_advising_satisfaction",
      "patterns": [
        "How satisfied are you with academic advising?",
        "Are the academic advisors helpful?"
      ],
      "responses": [
        "Our academic advising services are highly regarded, and students find them very helpful. Our dedicated advisors provide guidance and support to help students make informed decisions about their academic journey."
      ]
    },
    {
      "tag": "on_campus_tutoring_programs",
      "patterns": [
        "Do students use any on-campus tutoring programs or writing centers?",
        "Are tutoring services available on campus?"
      ],
      "responses": [
        "Yes, we have on-campus tutoring programs and writing centers where students can seek additional help and support in their studies."
      ]
    },
    {
      "tag": "class_sizes",
      "patterns": [
        "How big are your classes?",
        "What is the average class size?"
      ],
      "responses": [
        "Our classes are designed to be interactive and conducive to learning. While some classes may be larger, we ensure that students receive personalized attention and support from the faculty."
      ]
    },
    {
      "tag": "professors_for_research",
      "patterns": [
        "Are professors available for research with students?",
        "Can students participate in research with faculty?"
      ],
      "responses": [
        "Yes, both part-time and full-time research internships are available for students starting from the second year up to the final year. Students can actively engage in research projects with faculty members and gain valuable research experience."
      ]
    },
    {
      "tag": "first_year_experience",
      "patterns": [
        "What's it like to be a first-year student here?",
        "Can you describe the first year experience?"
      ],
      "responses": [
        "The first year at Shri Ramdeobaba College of Engineering and Management is a transformative and enriching experience for students. It is a time of making new friends, adapting to college life, exploring academic interests, and being a part of various clubs and activities."
      ]
    },
    {
      "tag": "activities_outside_class",
      "patterns": [
        "What do you do when you're not in class?",
        "What are the activities available on campus?"
      ],
      "responses": [
        "Outside of class, students can enjoy various activities such as having a meal at the canteen, relaxing in the open-air theatre, studying in the library, or engaging in sports and games on the playground."
      ]
    },
    {
      "tag": "food_quality_on_campus",
      "patterns": [
        "How’s the food on campus?",
        "Tell me about the quality of food in the canteen."
      ],
      "responses": [
        "The food in the canteen is known for its good quality and affordability. Students can enjoy a variety of dishes that cater to different tastes and preferences."
      ]
    },
    {
      "tag": "on_campus_residence",
      "patterns": [
        "Do most students live on-campus?",
        "Are on-campus hostels available?"
      ],
      "responses": [
        "Yes, we provide facilities for both girls and boys hostels, and many students choose to live on-campus for convenience and the vibrant college community."
      ]
    },
    {
      "tag": "dorm_quality",
      "patterns": [
        "How are the dorms?",
        "What's the quality of the dormitories?"
      ],
      "responses": [
        "The dorms at Shri Ramdeobaba College of Engineering and Management are of good quality, providing comfortable living spaces for students during their stay on-campus."
      ]
    },
    {
      "tag": "popular_student_organizations",
      "patterns": [
        "Which clubs and student organizations are popular?",
        "Tell me about the popular student clubs."
      ],
      "responses": [
        "Our college has a diverse range of student organizations and clubs. Some of the popular ones include the TECHNICAL CLUB, DRAMA CLUB, DANCE CLUB, MUSIC CLUB, PHOTOGRAPHY CLUB, READERS' REVERIE LITERARY CLUB, ROBOTICS CLUB, SAE-INDIA CLUB, EMBEDDED CLUB, ROTARACT CLUB, CODE BREAKERS CLUB, and SRC (Student Representative Council), among others."
      ]
    },
    {
      "tag": "student_club_membership",
      "patterns": [
        "Do lots of students belong to clubs?",
        "Are many students involved in student clubs?"
      ],
      "responses": [
        "Yes, many students actively participate in various student clubs and organizations. Students can audition and join clubs of their interest, allowing them to explore their passions and talents outside of academics."
      ]
    },
    {
      "tag": "favorite_campus_spots",
      "patterns": [
        "What's the best place on campus?",
        "Where do students love spending time on campus?"
      ],
      "responses": [
        "The best place on campus depends on personal preferences. For foodies, the canteen is a favorite spot. Social individuals enjoy the open-air theatre for gatherings and events, while sports enthusiasts appreciate the playground. Studious students often prefer the library's reading room for peaceful study sessions."
      ]
    },
    {
      "tag": "study_spots_on_campus",
      "patterns": [
        "Where do people study on campus?",
        "What are the study spots available on campus?"
      ],
      "responses": [
        "Students can find quiet study spots on campus in empty classrooms within their department or utilize the library's reading room for focused studying."
      ]
    },
    {
      "tag": "campus_facilities",
      "patterns": [
        "What are the facilities like (science labs, libraries, theatres, gyms, etc.)?",
        "Tell me about the available campus facilities."
      ],
      "responses": [
        "Our college boasts excellent facilities, including well-equipped science labs, modern libraries, state-of-the-art theatres, and fitness gyms to cater to students' academic and extracurricular needs."
      ]
    },
    {
      "tag": "computer_labs_availability",
      "patterns": [
        "Are there enough computer labs?",
        "Do you have sufficient computer facilities?"
      ],
      "responses": [
        "Yes, we have computer labs in every department to cater to the technological needs of students and support their academic activities."
      ]
    },
    {
      "tag": "wifi_quality_on_campus",
      "patterns": [
        "How is the WiFi on campus?",
        "Is the campus WiFi reliable?"
      ],
      "responses": [
        "The WiFi on campus is reliable and easily accessible, enabling students to stay connected and access online resources without any difficulty."
      ]
    },
    {
      "tag": "sports_popularity_on_campus",
      "patterns": [
        "Are sports popular?",
        "Do students actively participate in sports?"
      ],
      "responses": [
        "Yes, sports are popular on campus. Students actively participate in various sports and games, such as Badminton, Basketball, Chess, Cricket, Football, Lawn-tennis, Swimming, Table-tennis, Volleyball, Tug of war, Best Physique, Power-lifting, and Adventure Sports."
      ]
    },
    {
      "tag": "school_spirit",
      "patterns": [
        "Is there a lot of school spirit?",
        "Do students have strong school pride?"
      ],
      "responses": [
        "Yes, there is a strong sense of school spirit at our college, especially during branch cups and various cultural and sports events. Students take pride in representing their departments and participate actively in college activities."
      ]
    },
    {
      "tag": "fellow_students_description",
      "patterns": [
        "How would you describe your fellow students?",
        "Can you tell me about the student community?"
      ],
      "responses": [
        "Our fellow students are supportive, friendly, and inclusive. The college environment encourages collaboration and mutual respect among students from diverse backgrounds and interests."
      ]
    },
    {
      "tag": "friendly_student_community",
      "patterns": [
        "Are the students here friendly?",
        "Do students get along well with each other?"
      ],
      "responses": [
        "Yes, the students at Shri Ramdeobaba College of Engineering and Management are very friendly and welcoming. The college promotes a positive and inclusive atmosphere, fostering strong bonds among students."
      ]
    },
    {
      "tag": "unique_student_body",
      "patterns": [
        "What makes the student body unique?",
        "Tell me about the uniqueness of the student community."
      ],
      "responses": [
        "The student body at our college is unique due to the active involvement of students in various academic and cultural activities. The Student Representative Council (SRC) plays a crucial role in supporting students' needs and empowering them in academic and extracurricular endeavors."
      ]
    },
    {
      "tag": "internship_opportunities",
      "patterns": [
        "Are internships available?",
        "Do students get opportunities for internships?"
      ],
      "responses": [
        "Yes, we provide internship opportunities through various programs, such as the RGSTC-TIFAC-MSME Internship Program. Students can gain valuable industry exposure and contribute to the growth of micro, small, and medium enterprises (MSMEs)."
      ]
    },
    {
      "tag": "career_services_support",
      "patterns": [
        "Is Career Services helpful?",
        "Do you offer support for career development?"
      ],
      "responses": [
        "Yes, our Career Services department is dedicated to supporting students in their career development journey. Visit the Training and Placement Cell website for more information about career opportunities and placement assistance."
      ]
    },
    {
      "tag": "mentorship_program",
      "patterns": [
        "Do you have a mentor?",
        "Is there a mentorship program?"
      ],
      "responses": [
        "Yes, we have a mentor-mentee scheme to provide guidance and support to students. Mentorship is an integral part of our college culture, fostering personal and academic growth among students."
      ]
    },
    {
      "tag": "college_programs_offered",
      "patterns": [
        "What programs does the college offer?",
        "Tell me about the available programs."
      ],
      "responses": [
        "We offer a wide range of programs, including Undergraduate (UG) courses, Post Graduate (PG) programs, and PhD programs. Students can choose from various disciplines based on their interests and career goals."
      ]
    },
    {
      "tag": "leadership_skills_opportunities",
      "patterns": [
        "Are there opportunities to build leadership skills on campus?",
        "Can students develop leadership skills here?"
      ],
      "responses": [
        "Yes, our college encourages students to develop leadership skills through various student organizations, club activities, and participation in college events and committees."
      ]
    },
    {
      "tag": "service_learning_opportunities",
      "patterns": [
        "What options exist for service learning in the community?",
        "Tell me about service learning opportunities."
      ],
      "responses": [
        "We offer service learning programs that allow students to engage with the community and make a positive impact through various social, cultural, and environmental initiatives."
      ]
    },
    {
      "tag": "campus_recruitment",
      "patterns": [
        "Do employers recruit students on campus?",
        "Are there on-campus job placements?"
      ],
      "responses": [
        "Yes, in the third and final year, numerous companies visit our campus for placements, offering job opportunities to our students across various disciplines."
      ]
    },
    {
      "tag": "summer_jobs_opportunities",
      "patterns": [
        "How easy is it to find summer jobs and other kinds of work through your school?",
        "Are there opportunities for summer jobs?"
      ],
      "responses": [
        "Yes, we provide part-time internships for six months, which also serve as summer job opportunities. Some internships also offer work-from-home options."
      ]
    },
    {
      "tag": "notable_alumni",
      "patterns": [
        "Who are some of the notable graduates from your college?",
        "Tell me about successful alumni."
      ],
      "responses": [
        "Shri Ramdeobaba College of Engineering and Management has produced several successful alumni who have excelled in their respective fields. Some notable alumni include Arvind Nahata, Neeraj Tiwari, Anshuman Tiwari, Hariharan Laxminarayanan, and many others."
      ]
    },
    {
      "tag": "alumni_association_presence",
      "patterns": [
        "How visible is your school's alumni association on campus?",
        "Tell me about the alumni association."
      ],
      "responses": [
        "Our school's alumni association is actively involved in campus activities and engages with current students and faculty. For more information about the alumni association, you can visit their website at https://www.rknecalumni.org/."
      ]
    },
    {
      "tag": "hands_on_experiences",
      "patterns": [
        "What kinds of hands-on or practical experiences have you had in and outside of the classroom?",
        "Tell me about practical experiences in and outside of the classroom."
      ],
      "responses": [
        "At Shri Ramdeobaba College of Engineering and Management, we believe in providing hands-on and practical experiences to enhance learning. Students participate in workshops, projects, internships, and industry visits to gain real-world exposure and develop practical skills."
      ]
    },
    {
      "tag": "student_societies_by_department",
      "patterns": [
        "How many departments are there, and are there any student societies specific to departments?",
        "Tell me about the student societies in each department."
      ],
      "responses": [
        '''We have multiple departments at our college, and each department has its specific student society. Some of them are:

        1. Electronics - ELECTROLITZ
        2. Electronics & Communication - COMMUNIQUE
        3. Computer Science & Engineering - COMPUSYS
        4. Information Technology - ALACRITY
        5. Industrial Engineering - IES
        6. Civil Engineering - CESA
        7. Mechanical Engineering - MECHASSO
        8. Electrical Engineering - EESA
        9. Electronics Design & Technology - GENESIS
        10. Integrated MBA - IMREC
        11. Master in Business Administration - DMT Forum
        12. Master in Computer Application - CHRYSALIS'''
      ]
    },
    {
      "tag": "entrepreneurship_opportunities",
      "patterns": [
        "Is there any opportunity for young budding entrepreneurs?",
        "Tell me about entrepreneurship opportunities."
      ],
      "responses": [
        "Yes, we have the OASIS-The Entrepreneurship Development Cell (EDC) at Shri Ramdeobaba College of Engineering & Management. The EDC encourages graduating engineers to consider self-employment as a career option. It promotes entrepreneurship through guest lectures, workshops, seminars, competitions, and industrial visits, fostering an innovation ecosystem that benefits both students and micro, small, and medium enterprises (MSMEs)."
      ]
    },
    {
      "tag": "more_questions",
      "patterns": [
        "I want to know more",
        "Tell me in detail",
        "I have more questions",
        "I want to know everything",
        "Tell me everything"
      ],
      "responses": [
        "If you have any more questions or need further information, you can visit our college website at http://www.rknec.edu/ for general details, admissions website at http://www.rknec.edu/Admissions/admissionlanding.aspx for admission-related inquiries, placements info at http://www.rknec.edu/Placement/Placements.aspx, and academic information at http://www.rknec.edu/Academics/Academics.aspx."
      ]
    }
  ]
}

"""In order to create our training data, there is first some things we must do to our data. Here is the list:


1.  Create a vocabulary of all of the words used in the patterns (recall the patterns are the queries posed by the user)

2.  Create a list of the classes — This is simply the tags of each intent

Create a list of all the patterns within the intents file

Create a list of all the associated tags to go with each pattern in the intents file
"""

# initializing lemmatizer to get stem of words
lemmatizer = WordNetLemmatizer()
# Each list to create
words = []
classes = []
doc_X = []
doc_y = []
# Loop through all the intents
# tokenize each pattern and append tokens to words, the patterns and
# the associated tag to their associated list
for intent in data["intents"]:
    for pattern in intent["patterns"]:
        tokens = nltk.word_tokenize(pattern)
        words.extend(tokens)
        doc_X.append(pattern)
        doc_y.append(intent["tag"])

    # add the tag to the classes if it's not there already
    if intent["tag"] not in classes:
        classes.append(intent["tag"])
# lemmatize all the words in the vocab and convert them to lowercase
# if the words don't appear in punctuation
words = [lemmatizer.lemmatize(word.lower()) for word in words if word not in string.punctuation]
# sorting the vocab and classes in alphabetical order and taking the # set to ensure no duplicates occur
words = sorted(set(words))
classes = sorted(set(classes))

print(words)

print(classes)

print(doc_X)

print(doc_y)

"""Neural Networks expect numerical values, and not words, to be fed into them, therefore, we first have to process our data so that a neural network could read what we are doing.

Next, we vectorize our text data corpus by using the “Tokenizer” class and it allows us to limit our vocabulary size up to some defined number.

When we use this class for the text pre-processing task, by default all punctuations will be removed, turning the texts into space-separated sequences of words, and these sequences are then split into lists of tokens.
They will then be indexed or vectorized.

In order to convert our data to numerical values, we are going to leverage a technique called bag of words.
"""

# list for training data
training = []
out_empty = [0] * len(classes)
# creating the bag of words model
for idx, doc in enumerate(doc_X):
    bow = []
    text = lemmatizer.lemmatize(doc.lower())
    for word in words:
        bow.append(1) if word in text else bow.append(0)
    # mark the index of class that the current pattern is associated

    output_row = list(out_empty)
    output_row[classes.index(doc_y[idx])] = 1
    # add the one hot encoded BoW and associated classes to training
    training.append([bow, output_row])
# shuffle the data and convert it to an array
random.shuffle(training)
training = np.array(training, dtype=object)
# split the features and target labels
train_X = np.array(list(training[:, 0]))
train_y = np.array(list(training[:, 1]))

"""# Model Training
We had defined our Neural Network architecture for the proposed model and for that we use the “Sequential” model class of Keras.
"""

# defining some parameters
input_shape = (len(train_X[0]),)
output_shape = len(train_y[0])
epochs = 130
# the deep learning model
model = Sequential()
model.add(Dense(128, input_shape=input_shape, activation="relu"))
model.add(Dropout(0.3))
model.add(Dense(64, activation="relu"))
model.add(Dropout(0.3))
model.add(Dense(output_shape, activation = "softmax"))
adam = tf.keras.optimizers.Adam(learning_rate=0.005)
model.compile(loss='categorical_crossentropy',optimizer=adam,metrics=["accuracy"])
print(model.summary())
train=model.fit(x=train_X, y=train_y, epochs=200,batch_size=5, verbose=1)

"""# Model Analysis
plotting training set accuracy and training set loss for comparison.
"""

plt.plot(train.history["accuracy"],label='training set accuracy')
plt.plot(train.history["loss"],label='training set loss')
plt.xlabel('epoch')
plt.legend()

"""create a while loop that allows a user to input some query which is then cleaned, meaning we take the tokens and lemmatize each word. After that, we convert our text to numeric values using our bag of words model and make a prediction of what tag in our intents the features best represent. From there, we would take a random response from our responses within that intents tag and use that to respond to the query."""

def clean_text(text):
  tokens = nltk.word_tokenize(text)
  tokens = [lemmatizer.lemmatize(word) for word in tokens]
  return tokens

def bag_of_words(text, vocab):
  tokens = clean_text(text)
  bow = [0] * len(vocab)
  for w in tokens:
    for idx, word in enumerate(vocab):
      if word == w:
        bow[idx] = 1
  return np.array(bow)

def pred_class(text, vocab, labels):
  bow = bag_of_words(text, vocab)
  result = model.predict(np.array([bow]))[0]
  thresh = 0.2
  y_pred = [[idx, res] for idx, res in enumerate(result) if res > thresh]

  y_pred.sort(key=lambda x: x[1], reverse=True)
  return_list = []
  for r in y_pred:
    return_list.append(labels[r[0]])
  return return_list

def get_response(intents_list, intents_json):
  tag = intents_list[0]
  list_of_intents = intents_json["intents"]
  for i in list_of_intents:
    if i["tag"] == tag:
      result = random.choice(i["responses"])
      break
  return result

"""Normal Interface"""

while True:
    message = input("User: ")
    if message.lower() == "quit":
        print("Chatbot: Goodbye!")
        break

    intents = pred_class(message, words, classes)
    result = get_response(intents, data)
    print("Chatbot: ", result)
#type quit to exit loop

!pip install gradio

import gradio as gr

def chatbot_interface(user_message):
    # Replace pred_class and get_response with your actual chatbot logic
    intents = pred_class(user_message, words, classes)
    result = get_response(intents, data)
    return result

# Create the Gradio interface
inputs = gr.inputs.Textbox(lines=2, placeholder="User: Type your message here...")
outputs = gr.outputs.Textbox()

gr.Interface(
    fn=chatbot_interface,  # The function to be called when the user interacts with the interface
    inputs=inputs,
    outputs=outputs,
    live=True,  # Set live=True to make the chatbot respond in real-time as the user types
    capture_session=True,  # Set capture_session=True to store the chat history in the interface
).launch()

import gradio as gr

def chatbot_interface(message):
    # Replace pred_class and get_response with your actual chatbot logic
    intents = pred_class(message, words, classes)
    result = get_response(intents, data)
    return result

# Define the input and output components for the Gradio interface
inputs = gr.inputs.Textbox(lines=2)  # No need to specify a placeholder here
outputs = gr.outputs.Textbox()

# Create the Gradio interface
gr.Interface(
    fn=chatbot_interface,  # The function to be called when the user interacts with the interface
    inputs=inputs,
    outputs=outputs,
    live=True,  # Set live=True to make the chatbot respond in real-time as the user types
    capture_session=True,  # Set capture_session=True to store the chat history in the interface
).launch()





